/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuctionState {
  'isStopped' : boolean,
  'playerId' : bigint,
  'highestBid' : number,
  'isFinalized' : boolean,
  'highestBidTeamId' : [] | [bigint],
  'isAssigning' : boolean,
  'fixedIncrement' : boolean,
  'startingBid' : number,
}
export interface BatsmanPerformance {
  'fours' : bigint,
  'playerId' : bigint,
  'runs' : bigint,
  'sixes' : bigint,
  'innings' : bigint,
  'ballsFaced' : bigint,
}
export interface BowlerPerformance {
  'maidens' : bigint,
  'overs' : number,
  'playerId' : bigint,
  'wickets' : bigint,
  'ballsBowled' : bigint,
  'runsConceded' : bigint,
}
export interface FielderPerformance {
  'stumpings' : bigint,
  'playerId' : bigint,
  'dismissals' : bigint,
  'catches' : bigint,
}
export interface MatchView {
  'bowlers' : Array<BowlerPerformance>,
  'awayTeamId' : bigint,
  'date' : string,
  'awayTeamWickets' : bigint,
  'awayTeamName' : string,
  'awayTeamRuns' : bigint,
  'homeTeamId' : bigint,
  'bowlersByInnings' : Array<[bigint, Array<BowlerPerformance>]>,
  'homeTeamWickets' : bigint,
  'matchId' : bigint,
  'homeTeamName' : string,
  'homeTeamRuns' : bigint,
  'fielders' : Array<FielderPerformance>,
  'batsmen' : Array<BatsmanPerformance>,
  'matchWinner' : string,
  'location' : string,
}
export interface Player { 'id' : bigint, 'name' : string, 'basePrice' : number }
export interface Team { 'id' : bigint, 'name' : string, 'totalPurse' : number }
export interface TeamBudget { 'team' : Team, 'remainingPurse' : number }
export interface TeamExtended {
  'id' : bigint,
  'ownerPrincipals' : Array<Principal>,
  'name' : string,
  'totalPurse' : number,
}
export interface TeamSummary {
  'team' : TeamExtended,
  'remainingPurse' : number,
  'roster' : Array<[Player, number]>,
}
export interface UserProfile { 'name' : string, 'teamId' : [] | [bigint] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBatsmanPerformance' : ActorMethod<
    [bigint, BatsmanPerformance],
    undefined
  >,
  'addBowlerPerformance' : ActorMethod<[bigint, BowlerPerformance], undefined>,
  'addBowlerPerformanceWithInnings' : ActorMethod<
    [bigint, BowlerPerformance, bigint],
    undefined
  >,
  'addFielderPerformance' : ActorMethod<
    [bigint, FielderPerformance],
    undefined
  >,
  'addPlayerToTeam' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignPlayerAfterAuction' : ActorMethod<[bigint], undefined>,
  /**
   * / Change the name of an owner. Any authenticated user can set owner names.
   */
  'changeOwnerName' : ActorMethod<[Principal, string], undefined>,
  /**
   * / Change the name of a team. Any authenticated user can change team names.
   */
  'changeTeamName' : ActorMethod<[bigint, string], undefined>,
  'clearOwnerName' : ActorMethod<[Principal], undefined>,
  'createMatch' : ActorMethod<
    [bigint, bigint, string, string, string, string],
    bigint
  >,
  'createPlayer' : ActorMethod<[string, number], undefined>,
  'createTeam' : ActorMethod<[string, number, Array<Principal>], undefined>,
  'deletePlayer' : ActorMethod<[bigint], undefined>,
  'generateFixtures' : ActorMethod<[string, string], undefined>,
  'getAllMatches' : ActorMethod<[], Array<[bigint, MatchView]>>,
  'getAllOwnerNames' : ActorMethod<[], Array<[Principal, string]>>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getAllTeamBudgets' : ActorMethod<[], Array<TeamBudget>>,
  'getAllTeamSummaries' : ActorMethod<[], Array<TeamSummary>>,
  'getAllTeams' : ActorMethod<[], Array<TeamExtended>>,
  'getAuctionState' : ActorMethod<[bigint], [] | [AuctionState]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExportData' : ActorMethod<
    [],
    [Array<TeamSummary>, Array<TeamExtended>, Array<Player>]
  >,
  'getMatchById' : ActorMethod<[bigint], [] | [MatchView]>,
  'getOwnerName' : ActorMethod<[Principal], [] | [string]>,
  'getPlayerTeamAssignmentsWithSoldAmount' : ActorMethod<
    [],
    Array<[bigint, [] | [bigint], number]>
  >,
  'getPlayersForTeam' : ActorMethod<[bigint], Array<Player>>,
  'getRemainingTeamPurse' : ActorMethod<[bigint], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeBid' : ActorMethod<[bigint, bigint, number], undefined>,
  /**
   * / Self-registration: any authenticated (non-anonymous) principal can register as a user
   */
  'registerAsUser' : ActorMethod<[], undefined>,
  'removePlayerFromTeam' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startAuction' : ActorMethod<[bigint, number, boolean], undefined>,
  'stopAuction' : ActorMethod<[bigint], undefined>,
  'updateBowlerPerformance' : ActorMethod<
    [bigint, BowlerPerformance, bigint],
    undefined
  >,
  'updateBowlerPerformanceForUpdate' : ActorMethod<
    [bigint, bigint, bigint, BowlerPerformance],
    undefined
  >,
  'updateInningsStart' : ActorMethod<[bigint, bigint], undefined>,
  'updateMatchResults' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, string],
    undefined
  >,
  'updatePlayer' : ActorMethod<[bigint, string, number], undefined>,
  'updateTeamOwners' : ActorMethod<[bigint, Array<Principal>], undefined>,
  'updateTeamPurse' : ActorMethod<[bigint, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];