/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BatsmanPerformance = IDL.Record({
  'fours' : IDL.Nat,
  'playerId' : IDL.Nat,
  'runs' : IDL.Nat,
  'sixes' : IDL.Nat,
  'innings' : IDL.Nat,
  'ballsFaced' : IDL.Nat,
});
export const BowlerPerformance = IDL.Record({
  'maidens' : IDL.Nat,
  'overs' : IDL.Float64,
  'playerId' : IDL.Nat,
  'wickets' : IDL.Nat,
  'ballsBowled' : IDL.Nat,
  'runsConceded' : IDL.Nat,
});
export const FielderPerformance = IDL.Record({
  'stumpings' : IDL.Nat,
  'playerId' : IDL.Nat,
  'dismissals' : IDL.Nat,
  'catches' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BallOutcome = IDL.Record({
  'wicket' : IDL.Bool,
  'runs' : IDL.Nat,
  'bowler' : IDL.Text,
  'runsRemainingInOver' : IDL.Nat,
  'wicketsRemainingInInnings' : IDL.Nat,
  'batsman' : IDL.Text,
  'wicketRemainingInOver' : IDL.Nat,
  'typeOfDismissal' : IDL.Opt(IDL.Text),
  'runsRemainingInInnings' : IDL.Nat,
});
export const InningBallByBall = IDL.Record({
  'overNumber' : IDL.Nat,
  'inningNumber' : IDL.Nat,
  'balls' : IDL.Vec(BallOutcome),
});
export const MatchView = IDL.Record({
  'bowlers' : IDL.Vec(BowlerPerformance),
  'awayTeamId' : IDL.Nat,
  'date' : IDL.Text,
  'awayTeamWickets' : IDL.Nat,
  'awayTeamName' : IDL.Text,
  'awayTeamRuns' : IDL.Nat,
  'homeTeamId' : IDL.Nat,
  'bowlersByInnings' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(BowlerPerformance))),
  'ballByBallData' : IDL.Opt(IDL.Vec(InningBallByBall)),
  'homeTeamWickets' : IDL.Nat,
  'matchId' : IDL.Nat,
  'homeTeamName' : IDL.Text,
  'homeTeamRuns' : IDL.Nat,
  'fielders' : IDL.Vec(FielderPerformance),
  'batsmen' : IDL.Vec(BatsmanPerformance),
  'matchWinner' : IDL.Text,
  'location' : IDL.Text,
});
export const MatchListView = IDL.Record({
  'bowlers' : IDL.Vec(BowlerPerformance),
  'isPublished' : IDL.Bool,
  'awayTeamId' : IDL.Nat,
  'date' : IDL.Text,
  'awayTeamWickets' : IDL.Nat,
  'awayTeamName' : IDL.Text,
  'shareableId' : IDL.Opt(IDL.Text),
  'awayTeamRuns' : IDL.Nat,
  'homeTeamId' : IDL.Nat,
  'bowlersByInnings' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(BowlerPerformance))),
  'ballByBallData' : IDL.Opt(IDL.Vec(InningBallByBall)),
  'homeTeamWickets' : IDL.Nat,
  'matchId' : IDL.Nat,
  'homeTeamName' : IDL.Text,
  'homeTeamRuns' : IDL.Nat,
  'fielders' : IDL.Vec(FielderPerformance),
  'batsmen' : IDL.Vec(BatsmanPerformance),
  'matchWinner' : IDL.Text,
  'location' : IDL.Text,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'basePrice' : IDL.Float64,
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'totalPurse' : IDL.Float64,
});
export const TeamBudget = IDL.Record({
  'team' : Team,
  'remainingPurse' : IDL.Float64,
});
export const TeamExtended = IDL.Record({
  'id' : IDL.Nat,
  'ownerPrincipals' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'totalPurse' : IDL.Float64,
});
export const TeamSummary = IDL.Record({
  'team' : TeamExtended,
  'remainingPurse' : IDL.Float64,
  'roster' : IDL.Vec(IDL.Tuple(Player, IDL.Float64)),
});
export const AuctionState = IDL.Record({
  'isStopped' : IDL.Bool,
  'playerId' : IDL.Nat,
  'highestBid' : IDL.Float64,
  'isFinalized' : IDL.Bool,
  'highestBidTeamId' : IDL.Opt(IDL.Nat),
  'isAssigning' : IDL.Bool,
  'fixedIncrement' : IDL.Bool,
  'startingBid' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'teamId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBatsmanPerformance' : IDL.Func([IDL.Nat, BatsmanPerformance], [], []),
  'addBowlerPerformance' : IDL.Func([IDL.Nat, BowlerPerformance], [], []),
  'addBowlerPerformanceWithInnings' : IDL.Func(
      [IDL.Nat, BowlerPerformance, IDL.Nat],
      [],
      [],
    ),
  'addFielderPerformance' : IDL.Func([IDL.Nat, FielderPerformance], [], []),
  'addPlayerToTeam' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPlayerAfterAuction' : IDL.Func([IDL.Nat], [], []),
  'changeOwnerName' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'changeTeamName' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'clearOwnerName' : IDL.Func([IDL.Principal], [], []),
  'createMatch' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createPlayer' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'createTeam' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Vec(IDL.Principal)],
      [],
      [],
    ),
  'deletePlayer' : IDL.Func([IDL.Nat], [], []),
  'generateFixtures' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllMatches' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, MatchView))],
      ['query'],
    ),
  'getAllMatchesWithMetadata' : IDL.Func(
      [],
      [IDL.Vec(MatchListView)],
      ['query'],
    ),
  'getAllOwnerNames' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      ['query'],
    ),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getAllTeamBudgets' : IDL.Func([], [IDL.Vec(TeamBudget)], ['query']),
  'getAllTeamSummaries' : IDL.Func([], [IDL.Vec(TeamSummary)], ['query']),
  'getAllTeams' : IDL.Func([], [IDL.Vec(TeamExtended)], ['query']),
  'getAuctionState' : IDL.Func([IDL.Nat], [IDL.Opt(AuctionState)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExportData' : IDL.Func(
      [],
      [IDL.Vec(TeamSummary), IDL.Vec(TeamExtended), IDL.Vec(Player)],
      ['query'],
    ),
  'getMatchById' : IDL.Func([IDL.Nat], [IDL.Opt(MatchView)], ['query']),
  'getOwnerName' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'getPlayerTeamAssignmentsWithSoldAmount' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Opt(IDL.Nat), IDL.Float64))],
      ['query'],
    ),
  'getPlayersForTeam' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], ['query']),
  'getPublishedScorecardByShareableId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MatchView)],
      ['query'],
    ),
  'getRemainingTeamPurse' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeBid' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Float64], [], []),
  'publishScorecard' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'registerAsUser' : IDL.Func([], [], []),
  'removePlayerFromTeam' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startAuction' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Bool], [], []),
  'stopAuction' : IDL.Func([IDL.Nat], [], []),
  'unpublishScorecard' : IDL.Func([IDL.Nat], [], []),
  'updateBallByBallData' : IDL.Func(
      [IDL.Nat, IDL.Vec(InningBallByBall)],
      [],
      [],
    ),
  'updateBowlerPerformance' : IDL.Func(
      [IDL.Nat, BowlerPerformance, IDL.Nat],
      [],
      [],
    ),
  'updateBowlerPerformanceForUpdate' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, BowlerPerformance],
      [],
      [],
    ),
  'updateInningsStart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateMatchResults' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updatePlayer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Float64], [], []),
  'updateTeamOwners' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Principal)], [], []),
  'updateTeamPurse' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BatsmanPerformance = IDL.Record({
    'fours' : IDL.Nat,
    'playerId' : IDL.Nat,
    'runs' : IDL.Nat,
    'sixes' : IDL.Nat,
    'innings' : IDL.Nat,
    'ballsFaced' : IDL.Nat,
  });
  const BowlerPerformance = IDL.Record({
    'maidens' : IDL.Nat,
    'overs' : IDL.Float64,
    'playerId' : IDL.Nat,
    'wickets' : IDL.Nat,
    'ballsBowled' : IDL.Nat,
    'runsConceded' : IDL.Nat,
  });
  const FielderPerformance = IDL.Record({
    'stumpings' : IDL.Nat,
    'playerId' : IDL.Nat,
    'dismissals' : IDL.Nat,
    'catches' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BallOutcome = IDL.Record({
    'wicket' : IDL.Bool,
    'runs' : IDL.Nat,
    'bowler' : IDL.Text,
    'runsRemainingInOver' : IDL.Nat,
    'wicketsRemainingInInnings' : IDL.Nat,
    'batsman' : IDL.Text,
    'wicketRemainingInOver' : IDL.Nat,
    'typeOfDismissal' : IDL.Opt(IDL.Text),
    'runsRemainingInInnings' : IDL.Nat,
  });
  const InningBallByBall = IDL.Record({
    'overNumber' : IDL.Nat,
    'inningNumber' : IDL.Nat,
    'balls' : IDL.Vec(BallOutcome),
  });
  const MatchView = IDL.Record({
    'bowlers' : IDL.Vec(BowlerPerformance),
    'awayTeamId' : IDL.Nat,
    'date' : IDL.Text,
    'awayTeamWickets' : IDL.Nat,
    'awayTeamName' : IDL.Text,
    'awayTeamRuns' : IDL.Nat,
    'homeTeamId' : IDL.Nat,
    'bowlersByInnings' : IDL.Vec(
      IDL.Tuple(IDL.Nat, IDL.Vec(BowlerPerformance))
    ),
    'ballByBallData' : IDL.Opt(IDL.Vec(InningBallByBall)),
    'homeTeamWickets' : IDL.Nat,
    'matchId' : IDL.Nat,
    'homeTeamName' : IDL.Text,
    'homeTeamRuns' : IDL.Nat,
    'fielders' : IDL.Vec(FielderPerformance),
    'batsmen' : IDL.Vec(BatsmanPerformance),
    'matchWinner' : IDL.Text,
    'location' : IDL.Text,
  });
  const MatchListView = IDL.Record({
    'bowlers' : IDL.Vec(BowlerPerformance),
    'isPublished' : IDL.Bool,
    'awayTeamId' : IDL.Nat,
    'date' : IDL.Text,
    'awayTeamWickets' : IDL.Nat,
    'awayTeamName' : IDL.Text,
    'shareableId' : IDL.Opt(IDL.Text),
    'awayTeamRuns' : IDL.Nat,
    'homeTeamId' : IDL.Nat,
    'bowlersByInnings' : IDL.Vec(
      IDL.Tuple(IDL.Nat, IDL.Vec(BowlerPerformance))
    ),
    'ballByBallData' : IDL.Opt(IDL.Vec(InningBallByBall)),
    'homeTeamWickets' : IDL.Nat,
    'matchId' : IDL.Nat,
    'homeTeamName' : IDL.Text,
    'homeTeamRuns' : IDL.Nat,
    'fielders' : IDL.Vec(FielderPerformance),
    'batsmen' : IDL.Vec(BatsmanPerformance),
    'matchWinner' : IDL.Text,
    'location' : IDL.Text,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'basePrice' : IDL.Float64,
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'totalPurse' : IDL.Float64,
  });
  const TeamBudget = IDL.Record({
    'team' : Team,
    'remainingPurse' : IDL.Float64,
  });
  const TeamExtended = IDL.Record({
    'id' : IDL.Nat,
    'ownerPrincipals' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'totalPurse' : IDL.Float64,
  });
  const TeamSummary = IDL.Record({
    'team' : TeamExtended,
    'remainingPurse' : IDL.Float64,
    'roster' : IDL.Vec(IDL.Tuple(Player, IDL.Float64)),
  });
  const AuctionState = IDL.Record({
    'isStopped' : IDL.Bool,
    'playerId' : IDL.Nat,
    'highestBid' : IDL.Float64,
    'isFinalized' : IDL.Bool,
    'highestBidTeamId' : IDL.Opt(IDL.Nat),
    'isAssigning' : IDL.Bool,
    'fixedIncrement' : IDL.Bool,
    'startingBid' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'teamId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBatsmanPerformance' : IDL.Func([IDL.Nat, BatsmanPerformance], [], []),
    'addBowlerPerformance' : IDL.Func([IDL.Nat, BowlerPerformance], [], []),
    'addBowlerPerformanceWithInnings' : IDL.Func(
        [IDL.Nat, BowlerPerformance, IDL.Nat],
        [],
        [],
      ),
    'addFielderPerformance' : IDL.Func([IDL.Nat, FielderPerformance], [], []),
    'addPlayerToTeam' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPlayerAfterAuction' : IDL.Func([IDL.Nat], [], []),
    'changeOwnerName' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'changeTeamName' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'clearOwnerName' : IDL.Func([IDL.Principal], [], []),
    'createMatch' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createPlayer' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'createTeam' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Vec(IDL.Principal)],
        [],
        [],
      ),
    'deletePlayer' : IDL.Func([IDL.Nat], [], []),
    'generateFixtures' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllMatches' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, MatchView))],
        ['query'],
      ),
    'getAllMatchesWithMetadata' : IDL.Func(
        [],
        [IDL.Vec(MatchListView)],
        ['query'],
      ),
    'getAllOwnerNames' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        ['query'],
      ),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getAllTeamBudgets' : IDL.Func([], [IDL.Vec(TeamBudget)], ['query']),
    'getAllTeamSummaries' : IDL.Func([], [IDL.Vec(TeamSummary)], ['query']),
    'getAllTeams' : IDL.Func([], [IDL.Vec(TeamExtended)], ['query']),
    'getAuctionState' : IDL.Func([IDL.Nat], [IDL.Opt(AuctionState)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExportData' : IDL.Func(
        [],
        [IDL.Vec(TeamSummary), IDL.Vec(TeamExtended), IDL.Vec(Player)],
        ['query'],
      ),
    'getMatchById' : IDL.Func([IDL.Nat], [IDL.Opt(MatchView)], ['query']),
    'getOwnerName' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
    'getPlayerTeamAssignmentsWithSoldAmount' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Opt(IDL.Nat), IDL.Float64))],
        ['query'],
      ),
    'getPlayersForTeam' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], ['query']),
    'getPublishedScorecardByShareableId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MatchView)],
        ['query'],
      ),
    'getRemainingTeamPurse' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeBid' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Float64], [], []),
    'publishScorecard' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'registerAsUser' : IDL.Func([], [], []),
    'removePlayerFromTeam' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startAuction' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Bool], [], []),
    'stopAuction' : IDL.Func([IDL.Nat], [], []),
    'unpublishScorecard' : IDL.Func([IDL.Nat], [], []),
    'updateBallByBallData' : IDL.Func(
        [IDL.Nat, IDL.Vec(InningBallByBall)],
        [],
        [],
      ),
    'updateBowlerPerformance' : IDL.Func(
        [IDL.Nat, BowlerPerformance, IDL.Nat],
        [],
        [],
      ),
    'updateBowlerPerformanceForUpdate' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, BowlerPerformance],
        [],
        [],
      ),
    'updateInningsStart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateMatchResults' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updatePlayer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Float64], [], []),
    'updateTeamOwners' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Principal)], [], []),
    'updateTeamPurse' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };