/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BatsmanPerformance = IDL.Record({
  'fours' : IDL.Nat,
  'playerId' : IDL.Nat,
  'runs' : IDL.Nat,
  'sixes' : IDL.Nat,
  'innings' : IDL.Nat,
  'ballsFaced' : IDL.Nat,
});
export const BowlerPerformance = IDL.Record({
  'maidens' : IDL.Nat,
  'overs' : IDL.Float64,
  'playerId' : IDL.Nat,
  'wickets' : IDL.Nat,
  'ballsBowled' : IDL.Nat,
  'runsConceded' : IDL.Nat,
});
export const FielderPerformance = IDL.Record({
  'stumpings' : IDL.Nat,
  'playerId' : IDL.Nat,
  'dismissals' : IDL.Nat,
  'catches' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Match = IDL.Record({
  'bowlers' : IDL.Vec(BowlerPerformance),
  'awayTeamId' : IDL.Nat,
  'date' : IDL.Text,
  'awayTeamWickets' : IDL.Nat,
  'awayTeamName' : IDL.Text,
  'awayTeamRuns' : IDL.Nat,
  'homeTeamId' : IDL.Nat,
  'homeTeamWickets' : IDL.Nat,
  'homeTeamName' : IDL.Text,
  'homeTeamRuns' : IDL.Nat,
  'fielders' : IDL.Vec(FielderPerformance),
  'batsmen' : IDL.Vec(BatsmanPerformance),
  'matchWinner' : IDL.Text,
  'location' : IDL.Text,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'basePrice' : IDL.Float64,
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'totalPurse' : IDL.Float64,
});
export const TeamBudget = IDL.Record({
  'team' : Team,
  'remainingPurse' : IDL.Float64,
});
export const AuctionState = IDL.Record({
  'isStopped' : IDL.Bool,
  'playerId' : IDL.Nat,
  'highestBid' : IDL.Float64,
  'isFinalized' : IDL.Bool,
  'highestBidTeamId' : IDL.Opt(IDL.Nat),
  'isAssigning' : IDL.Bool,
  'fixedIncrement' : IDL.Bool,
  'startingBid' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'teamId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBatsmanPerformance' : IDL.Func([IDL.Nat, BatsmanPerformance], [], []),
  'addBowlerPerformance' : IDL.Func([IDL.Nat, BowlerPerformance], [], []),
  'addFielderPerformance' : IDL.Func([IDL.Nat, FielderPerformance], [], []),
  'addPlayerToTeam' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPlayerAfterAuction' : IDL.Func([IDL.Nat], [], []),
  'createMatch' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createPlayer' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'createTeam' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'deletePlayer' : IDL.Func([IDL.Nat], [], []),
  'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getAllTeamBudgets' : IDL.Func([], [IDL.Vec(TeamBudget)], ['query']),
  'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getAuctionState' : IDL.Func([IDL.Nat], [IDL.Opt(AuctionState)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatchById' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
  'getPlayerTeamAssignments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Opt(IDL.Nat)))],
      ['query'],
    ),
  'getPlayersForTeam' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], ['query']),
  'getRemainingTeamPurse' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeBid' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Float64], [], []),
  'removePlayerFromTeam' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startAuction' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Bool], [], []),
  'stopAuction' : IDL.Func([IDL.Nat], [], []),
  'updateMatchResults' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updatePlayer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Float64], [], []),
  'updateTeamPurse' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BatsmanPerformance = IDL.Record({
    'fours' : IDL.Nat,
    'playerId' : IDL.Nat,
    'runs' : IDL.Nat,
    'sixes' : IDL.Nat,
    'innings' : IDL.Nat,
    'ballsFaced' : IDL.Nat,
  });
  const BowlerPerformance = IDL.Record({
    'maidens' : IDL.Nat,
    'overs' : IDL.Float64,
    'playerId' : IDL.Nat,
    'wickets' : IDL.Nat,
    'ballsBowled' : IDL.Nat,
    'runsConceded' : IDL.Nat,
  });
  const FielderPerformance = IDL.Record({
    'stumpings' : IDL.Nat,
    'playerId' : IDL.Nat,
    'dismissals' : IDL.Nat,
    'catches' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Match = IDL.Record({
    'bowlers' : IDL.Vec(BowlerPerformance),
    'awayTeamId' : IDL.Nat,
    'date' : IDL.Text,
    'awayTeamWickets' : IDL.Nat,
    'awayTeamName' : IDL.Text,
    'awayTeamRuns' : IDL.Nat,
    'homeTeamId' : IDL.Nat,
    'homeTeamWickets' : IDL.Nat,
    'homeTeamName' : IDL.Text,
    'homeTeamRuns' : IDL.Nat,
    'fielders' : IDL.Vec(FielderPerformance),
    'batsmen' : IDL.Vec(BatsmanPerformance),
    'matchWinner' : IDL.Text,
    'location' : IDL.Text,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'basePrice' : IDL.Float64,
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'totalPurse' : IDL.Float64,
  });
  const TeamBudget = IDL.Record({
    'team' : Team,
    'remainingPurse' : IDL.Float64,
  });
  const AuctionState = IDL.Record({
    'isStopped' : IDL.Bool,
    'playerId' : IDL.Nat,
    'highestBid' : IDL.Float64,
    'isFinalized' : IDL.Bool,
    'highestBidTeamId' : IDL.Opt(IDL.Nat),
    'isAssigning' : IDL.Bool,
    'fixedIncrement' : IDL.Bool,
    'startingBid' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'teamId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBatsmanPerformance' : IDL.Func([IDL.Nat, BatsmanPerformance], [], []),
    'addBowlerPerformance' : IDL.Func([IDL.Nat, BowlerPerformance], [], []),
    'addFielderPerformance' : IDL.Func([IDL.Nat, FielderPerformance], [], []),
    'addPlayerToTeam' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPlayerAfterAuction' : IDL.Func([IDL.Nat], [], []),
    'createMatch' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createPlayer' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'createTeam' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'deletePlayer' : IDL.Func([IDL.Nat], [], []),
    'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getAllTeamBudgets' : IDL.Func([], [IDL.Vec(TeamBudget)], ['query']),
    'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getAuctionState' : IDL.Func([IDL.Nat], [IDL.Opt(AuctionState)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatchById' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
    'getPlayerTeamAssignments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Opt(IDL.Nat)))],
        ['query'],
      ),
    'getPlayersForTeam' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], ['query']),
    'getRemainingTeamPurse' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeBid' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Float64], [], []),
    'removePlayerFromTeam' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startAuction' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Bool], [], []),
    'stopAuction' : IDL.Func([IDL.Nat], [], []),
    'updateMatchResults' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updatePlayer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Float64], [], []),
    'updateTeamPurse' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };