/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'basePrice' : IDL.Float64,
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'totalPurse' : IDL.Float64,
});
export const TeamBudget = IDL.Record({
  'team' : Team,
  'remainingPurse' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'teamId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPlayerToTeam' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPrincipalToTeam' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'createPlayer' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'createTeam' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'deletePlayer' : IDL.Func([IDL.Nat], [], []),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getAllTeamBudgets' : IDL.Func([], [IDL.Vec(TeamBudget)], ['query']),
  'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlayersForTeam' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], ['query']),
  'getRemainingTeamPurse' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removePlayerFromTeam' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePlayer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Float64], [], []),
  'updateTeamPurse' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'basePrice' : IDL.Float64,
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'totalPurse' : IDL.Float64,
  });
  const TeamBudget = IDL.Record({
    'team' : Team,
    'remainingPurse' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'teamId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPlayerToTeam' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPrincipalToTeam' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'createPlayer' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'createTeam' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'deletePlayer' : IDL.Func([IDL.Nat], [], []),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getAllTeamBudgets' : IDL.Func([], [IDL.Vec(TeamBudget)], ['query']),
    'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlayersForTeam' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], ['query']),
    'getRemainingTeamPurse' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removePlayerFromTeam' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePlayer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Float64], [], []),
    'updateTeamPurse' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };