/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: bigint;
    name: string;
    basePrice: number;
}
export interface BowlerPerformance {
    maidens: bigint;
    overs: number;
    playerId: bigint;
    wickets: bigint;
    ballsBowled: bigint;
    runsConceded: bigint;
}
export interface TeamExtended {
    id: bigint;
    ownerPrincipals: Array<Principal>;
    name: string;
    totalPurse: number;
}
export interface BatsmanPerformance {
    fours: bigint;
    playerId: bigint;
    runs: bigint;
    sixes: bigint;
    innings: bigint;
    ballsFaced: bigint;
}
export interface TeamSummary {
    team: TeamExtended;
    remainingPurse: number;
    roster: Array<[Player, number]>;
}
export interface FielderPerformance {
    stumpings: bigint;
    playerId: bigint;
    dismissals: bigint;
    catches: bigint;
}
export interface AuctionState {
    isStopped: boolean;
    playerId: bigint;
    highestBid: number;
    isFinalized: boolean;
    highestBidTeamId?: bigint;
    isAssigning: boolean;
    fixedIncrement: boolean;
    startingBid: number;
}
export interface MatchView {
    bowlers: Array<BowlerPerformance>;
    awayTeamId: bigint;
    date: string;
    awayTeamWickets: bigint;
    awayTeamName: string;
    awayTeamRuns: bigint;
    homeTeamId: bigint;
    bowlersByInnings: Array<[bigint, Array<BowlerPerformance>]>;
    homeTeamWickets: bigint;
    matchId: bigint;
    homeTeamName: string;
    homeTeamRuns: bigint;
    fielders: Array<FielderPerformance>;
    batsmen: Array<BatsmanPerformance>;
    matchWinner: string;
    location: string;
}
export interface TeamBudget {
    team: Team;
    remainingPurse: number;
}
export interface UserProfile {
    name: string;
    teamId?: bigint;
}
export interface Team {
    id: bigint;
    name: string;
    totalPurse: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBatsmanPerformance(matchId: bigint, performance: BatsmanPerformance): Promise<void>;
    addBowlerPerformance(matchId: bigint, performance: BowlerPerformance): Promise<void>;
    addBowlerPerformanceWithInnings(matchId: bigint, performance: BowlerPerformance, innings: bigint): Promise<void>;
    addFielderPerformance(matchId: bigint, performance: FielderPerformance): Promise<void>;
    addPlayerToTeam(playerId: bigint, teamId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignPlayerAfterAuction(playerId: bigint): Promise<void>;
    /**
     * / Change the name of an owner. Any authenticated user can set owner names.
     */
    changeOwnerName(owner: Principal, name: string): Promise<void>;
    /**
     * / Change the name of a team. Any authenticated user can change team names.
     */
    changeTeamName(teamId: bigint, name: string): Promise<void>;
    clearOwnerName(owner: Principal): Promise<void>;
    createMatch(homeTeamId: bigint, awayTeamId: bigint, homeTeamName: string, awayTeamName: string, date: string, location: string): Promise<bigint>;
    createPlayer(name: string, basePrice: number): Promise<void>;
    createTeam(name: string, totalPurse: number, ownerPrincipals: Array<Principal>): Promise<void>;
    deletePlayer(playerId: bigint): Promise<void>;
    generateFixtures(tournamentName: string, startDate: string): Promise<void>;
    getAllMatches(): Promise<Array<[bigint, MatchView]>>;
    getAllOwnerNames(): Promise<Array<[Principal, string]>>;
    getAllPlayers(): Promise<Array<Player>>;
    getAllTeamBudgets(): Promise<Array<TeamBudget>>;
    getAllTeamSummaries(): Promise<Array<TeamSummary>>;
    getAllTeams(): Promise<Array<TeamExtended>>;
    getAuctionState(playerId: bigint): Promise<AuctionState | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExportData(): Promise<[Array<TeamSummary>, Array<TeamExtended>, Array<Player>]>;
    getMatchById(matchId: bigint): Promise<MatchView | null>;
    getOwnerName(owner: Principal): Promise<string | null>;
    getPlayerTeamAssignmentsWithSoldAmount(): Promise<Array<[bigint, bigint | null, number]>>;
    getPlayersForTeam(teamId: bigint): Promise<Array<Player>>;
    getRemainingTeamPurse(teamId: bigint): Promise<number>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    placeBid(playerId: bigint, teamId: bigint, bidAmount: number): Promise<void>;
    /**
     * / Self-registration: any authenticated (non-anonymous) principal can register as a user
     */
    registerAsUser(): Promise<void>;
    removePlayerFromTeam(playerId: bigint, teamId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    startAuction(playerId: bigint, startingBid: number, fixedIncrement: boolean): Promise<void>;
    stopAuction(playerId: bigint): Promise<void>;
    updateBowlerPerformance(matchId: bigint, performance: BowlerPerformance, innings: bigint): Promise<void>;
    updateBowlerPerformanceForUpdate(matchId: bigint, playerId: bigint, innings: bigint, updatedPerformance: BowlerPerformance): Promise<void>;
    updateInningsStart(matchId: bigint, innings: bigint): Promise<void>;
    updateMatchResults(matchId: bigint, homeTeamRuns: bigint, homeTeamWickets: bigint, awayTeamRuns: bigint, awayTeamWickets: bigint, matchWinner: string): Promise<void>;
    updatePlayer(playerId: bigint, name: string, basePrice: number): Promise<void>;
    updateTeamOwners(teamId: bigint, newOwnerPrincipals: Array<Principal>): Promise<void>;
    updateTeamPurse(teamId: bigint, newPurse: number): Promise<void>;
}
import type { AuctionState as _AuctionState, MatchView as _MatchView, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBatsmanPerformance(arg0: bigint, arg1: BatsmanPerformance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBatsmanPerformance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBatsmanPerformance(arg0, arg1);
            return result;
        }
    }
    async addBowlerPerformance(arg0: bigint, arg1: BowlerPerformance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBowlerPerformance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBowlerPerformance(arg0, arg1);
            return result;
        }
    }
    async addBowlerPerformanceWithInnings(arg0: bigint, arg1: BowlerPerformance, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBowlerPerformanceWithInnings(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBowlerPerformanceWithInnings(arg0, arg1, arg2);
            return result;
        }
    }
    async addFielderPerformance(arg0: bigint, arg1: FielderPerformance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFielderPerformance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFielderPerformance(arg0, arg1);
            return result;
        }
    }
    async addPlayerToTeam(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayerToTeam(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayerToTeam(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignPlayerAfterAuction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignPlayerAfterAuction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignPlayerAfterAuction(arg0);
            return result;
        }
    }
    async changeOwnerName(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changeOwnerName(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeOwnerName(arg0, arg1);
            return result;
        }
    }
    async changeTeamName(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changeTeamName(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeTeamName(arg0, arg1);
            return result;
        }
    }
    async clearOwnerName(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearOwnerName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearOwnerName(arg0);
            return result;
        }
    }
    async createMatch(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createPlayer(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayer(arg0, arg1);
            return result;
        }
    }
    async createTeam(arg0: string, arg1: number, arg2: Array<Principal>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeam(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeam(arg0, arg1, arg2);
            return result;
        }
    }
    async deletePlayer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlayer(arg0);
            return result;
        }
    }
    async generateFixtures(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.generateFixtures(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateFixtures(arg0, arg1);
            return result;
        }
    }
    async getAllMatches(): Promise<Array<[bigint, MatchView]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return result;
        }
    }
    async getAllOwnerNames(): Promise<Array<[Principal, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOwnerNames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOwnerNames();
            return result;
        }
    }
    async getAllPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return result;
        }
    }
    async getAllTeamBudgets(): Promise<Array<TeamBudget>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeamBudgets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeamBudgets();
            return result;
        }
    }
    async getAllTeamSummaries(): Promise<Array<TeamSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeamSummaries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeamSummaries();
            return result;
        }
    }
    async getAllTeams(): Promise<Array<TeamExtended>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeams();
            return result;
        }
    }
    async getAuctionState(arg0: bigint): Promise<AuctionState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuctionState(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuctionState(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExportData(): Promise<[Array<TeamSummary>, Array<TeamExtended>, Array<Player>]> {
        if (this.processError) {
            try {
                const result = await this.actor.getExportData();
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExportData();
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async getMatchById(arg0: bigint): Promise<MatchView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchById(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchById(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnerName(arg0: Principal): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerName(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerName(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerTeamAssignmentsWithSoldAmount(): Promise<Array<[bigint, bigint | null, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerTeamAssignmentsWithSoldAmount();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerTeamAssignmentsWithSoldAmount();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayersForTeam(arg0: bigint): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersForTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersForTeam(arg0);
            return result;
        }
    }
    async getRemainingTeamPurse(arg0: bigint): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemainingTeamPurse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemainingTeamPurse(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeBid(arg0: bigint, arg1: bigint, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBid(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBid(arg0, arg1, arg2);
            return result;
        }
    }
    async registerAsUser(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAsUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAsUser();
            return result;
        }
    }
    async removePlayerFromTeam(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePlayerFromTeam(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePlayerFromTeam(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async startAuction(arg0: bigint, arg1: number, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startAuction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startAuction(arg0, arg1, arg2);
            return result;
        }
    }
    async stopAuction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.stopAuction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stopAuction(arg0);
            return result;
        }
    }
    async updateBowlerPerformance(arg0: bigint, arg1: BowlerPerformance, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBowlerPerformance(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBowlerPerformance(arg0, arg1, arg2);
            return result;
        }
    }
    async updateBowlerPerformanceForUpdate(arg0: bigint, arg1: bigint, arg2: bigint, arg3: BowlerPerformance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBowlerPerformanceForUpdate(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBowlerPerformanceForUpdate(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateInningsStart(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInningsStart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInningsStart(arg0, arg1);
            return result;
        }
    }
    async updateMatchResults(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMatchResults(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMatchResults(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updatePlayer(arg0: bigint, arg1: string, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayer(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTeamOwners(arg0: bigint, arg1: Array<Principal>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamOwners(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamOwners(arg0, arg1);
            return result;
        }
    }
    async updateTeamPurse(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamPurse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamPurse(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AuctionState_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuctionState): AuctionState {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchView]): MatchView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AuctionState]): AuctionState | null {
    return value.length === 0 ? null : from_candid_AuctionState_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isStopped: boolean;
    playerId: bigint;
    highestBid: number;
    isFinalized: boolean;
    highestBidTeamId: [] | [bigint];
    isAssigning: boolean;
    fixedIncrement: boolean;
    startingBid: number;
}): {
    isStopped: boolean;
    playerId: bigint;
    highestBid: number;
    isFinalized: boolean;
    highestBidTeamId?: bigint;
    isAssigning: boolean;
    fixedIncrement: boolean;
    startingBid: number;
} {
    return {
        isStopped: value.isStopped,
        playerId: value.playerId,
        highestBid: value.highestBid,
        isFinalized: value.isFinalized,
        highestBidTeamId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.highestBidTeamId)),
        isAssigning: value.isAssigning,
        fixedIncrement: value.fixedIncrement,
        startingBid: value.startingBid
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    teamId: [] | [bigint];
}): {
    name: string;
    teamId?: bigint;
} {
    return {
        name: value.name,
        teamId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.teamId))
    };
}
function from_candid_tuple_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, [] | [bigint], number]): [bigint, bigint | null, number] {
    return [
        value[0],
        from_candid_opt_n6(_uploadFile, _downloadFile, value[1]),
        value[2]
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, [] | [bigint], number]>): Array<[bigint, bigint | null, number]> {
    return value.map((x)=>from_candid_tuple_n15(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    teamId?: bigint;
}): {
    name: string;
    teamId: [] | [bigint];
} {
    return {
        name: value.name,
        teamId: value.teamId ? candid_some(value.teamId) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
